[project]
name = "dashboard-mockup"
version = "0.1.0"
description = "Dashboard to demonstrate streamlit."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "streamlit-option-menu>=0.4.0",
    "streamlit>=1.39.0",
]
